### ISSUE TITLE
Build fails with latest llvm

### ISSUE THREAD

**Issue by ruedbi** [dougpuob/cppnamelint#54]
ok, not really a bug, as it should work with llvm 8 only ...
LLVM_DIR_CPPNAMELINT_PATH  : xxx/llvm-project/build/**release**/lib
is wrong for me, I have xxx/llvm-project/build/lib only; fixed it with a link
then I get:
/usr/bin/ld: cannot find -lclangToolingRefactor (which is now called libclangToolingRefactoring)
/usr/bin/ld: cannot find -lLLVMX86AsmPrinter (not available in my build)
Just removing these libs from CMakeLists.txt was not successfull (no surprise).

I did some more tests to get that fixed.
By adding all llvm-13 libs to the CMakeLists.txt I was finally able to build cppnamelint, but then I get a runtime error:
: CommandLine Error: Option 'opt-bisect-limit' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
which indicates a library load issue which I could not solve in a reasonable time.
But at least it looks as if an update to latest llvm is possible.

**Comment by dougpuob** [comment]
Hi @ruedbi 
Happy to know someone is interested in this project too. This project is based on LLVM v8.0, LLVM is growing faster, in the middle while, libraries or interfaces are possibly changed. So build this project with LLVM v8.0.

Have fun.

**Comment by dougpuob** [comment]
Hi @ruedbi , I integrated this project with Azure CI/CD, the pre-built library is 8.0.0. I am trying use library from vcpkg. So I can't update current buildable CMakeLists.txt directly.

**Comment by dougpuob** [comment]
Hi @ruedbi , it supports to build with newer llvm version. Thank you for your report.
